version: '3'

services:
    
    php:
        build: ./docker/php
        container_name: php7-apache
        ports:
         - "80:80"
        volumes:
            - ./www:/var/www/html
        restart: always
        depends_on:
          - db
        
    db:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306
        volumes:
            - "./backup/db/mysql:/var/lib/mysql"

